version: "3"
services:

  s3-media-web-server:
    image: nginx:latest

    expose:
      - "80"

    networks:
      - appnet
      - nginx-proxy


  s3-media-transcoder:
    restart: always
    build: .

    networks:
      - appnet

    external_links:
      - docker-rabbitmq:rabbitmq
      - docker-mongo:mongodb
      


  s3-media-transcoder-worker:
    restart: always
    build: .
    command: ["/src/application/CLI/Commands/listen-for-video-transcoding-jobs.php"]

    networks:
      - appnet
      - nginx-proxy

    external_links:
      - docker-rabbitmq:rabbitmq
      - docker-mongo:mongodb



  s3-media-abandonned-file-searcher:
    build: .
    command: ["/src/application/CLI/Commands/search-abandonned-files.php"]

    networks:
      - appnet
      - nginx-proxy

    external_links:
      - docker-rabbitmq:rabbitmq
      - docker-mongo:mongodb
  
  
networks:

  nginx-proxy:
    external: true

  appnet:
    external: true
    
    
  
  